[phases.setup]
nixpkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = []

[phases.start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port 8000"
