name: Youtube Trends Daily ETL

on:
  schedule:
    - cron: "0 5 * * *" # Runs at 5 AM UTC daily
  workflow_dispatch: # Allows manual triggering

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run ETL script
        env:
          SQL_DB_URL: ${{ secrets.SQL_DB_URL }}
          YOUTUBE_API: ${{ secrets.YOUTUBE_API }}
        run: python youtube_trends/main.py
